spring.datasource.url: jdbc:mysql://localhost:3306/todolist?serverTimezone=UTC&useSSL=false
spring.datasource.username: root
spring.datasource.password: afrby736132
spring.jpa.hibernate.ddl-auto: none
someParameter:
  value: 5463